meta_product_name: "Karuna"
meta_title: "Karuna · Compassion is action"
meta_description: "Volunteer for projects that matter and help make the change happen."
meta_image: "cover.png" # should exist in `app/assets/images/`
